# Generated by Django 3.2.14 on 2024-07-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_delete_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.TextField(),
        ),
    ]
